# Gradle
org.gradle.jvmargs=-Xmx3G

# Project
version=1.1.7.1
last_mod_version=1.1.6.2
group=com.github.wendall911.actuallyharvest

# Common
minecraft_version=26.1.1
mixin_extras_version=0.3.5
whitenoise_version=2.0.7
whitenoise_range=[2.0.0,3.0.0)
fabric_whitenoise_range=[">=2.0.0","<=3.0.0"]
mixin_version=0.8.5
java_version=25

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.1.1.1-beta
neoforge_loader_version_range=[4,)
neoforge_mc_version_range=[26.1, 26.2)
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.1-1

# Fabric
# https://fabricmc.net/develop/
fabric_version=0.145.2+26.1.1
fabric_api_min_version=>=0.143.10
fabric_loader_version=0.18.6
fabric_loader_min_version=>=0.15
fabric_mc_version_range=[">26.1-"]
# https://www.curseforge.com/minecraft/mc-mods/modmenu/files/all
mod_menu_version=18.0.0-alpha.8

# Integration and Testing Mods
# https://www.curseforge.com/minecraft/mc-mods/jei/files/all
jei_version=29.2.0.20
jei_minecraft_version=26.1
# https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items/files/all
rei_version=21.9.812
# https://www.curseforge.com/minecraft/mc-mods/architectury-api/files/all
architectury_version=18.0.8
# https://www.curseforge.com/minecraft/mc-mods/cloth-config/files/all
cloth_config_version=26.1.154
farmers_delight_neoforge_version=???
phc_crops_neoforge_version=???
phc_trees_neoforge_version=???
ephero_lib_neoforge_version=???
ephero_lib_fabric_version=???
croptopia_neoforge_version=???
croptopia_fabric_version=???
kiwi_neoforge_version=???
lychee_neoforge_version=???
fruit_trees_neoforge_version=???
terrablender_version=???
byg_version=???
tyg_version=???
corgilib_version=???
geckolib_version=???
architectury_fabric_version=???
architectury_neoforge_version=???
ld_flower_breeding_version=???
create_version=???
moonlight_neoforge_version=???
supplementaries_neoforge_version=???
ie_neoforge_version=???
# https://www.curseforge.com/minecraft/mc-mods/lets-do-brewery-farm-charm-compat/files/all
letsdo_brewery_neoforge_version=???
letsdo_brewery_fabric_version=???
# https://www.curseforge.com/minecraft/mc-mods/lets-do-herbal-brews/files/all
letsdo_herbal_neoforge_version=???
letsdo_herbal_fabric_version=???
# https://www.curseforge.com/minecraft/mc-mods/lets-do-farm-charm/files/all
letsdo_farm_neoforge_version=???
letsdo_farm_fabric_version=???
# https://www.curseforge.com/minecraft/mc-mods/lets-do-vinery/files/all
letsdo_vinery_neoforge_version=???
letsdo_vinery_fabric_version=???

# Mod options
mod_display_name=Actually Harvest
mod_name=ActuallyHarvest
mod_id=actuallyharvest
mod_author=wendall911
mod_credits=Knoface
license=MIT
mod_description=Working right click harvest. For modded minecraft!
mod_update_branch=26.1

# CurseForge/Modrinth Options
curseforge_api_key_prop=ahcurseApiKey
curseforge_id=1076278
curseforge_slug=actually-harvest
modrinth_api_key_prop=modrinthKey
modrinth_id=sUbuUC7R
discord_webhook_prop=ahDiscordWebhook
discord_dryrun_webhook_prop=discordDryrunWebhook
release_type=release
release_versions=26.1,26.1.1
