# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Project
version=1.1.2.1
last_mod_version=1.1.1.1
neoforge_mod_version=1.21.4-1.1.2.1-NEOFORGE
fabric_mod_version=1.21.4-1.1.2.1-FABRIC
java_version=21

# Common
minecraft_version=1.21.4

# Fabric
# https://fabricmc.net/develop/
fabric_version=0.111.0+1.21.4
fabric_loader_version=0.16.9
fabric_loader_min_version=>=0.15
fabric_mc_version_range=["1.21.3","1.21.4"]
mod_menu_version=12.0.0-beta.1

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.4.20-beta
neoforge_loader_version_range=[21.0.143,)
neoforge_mc_version_range=[1.21.2, 1.22)
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.4-20241203.161809

# Mappings
parchment_mc_version=1.21
parchment_version=2024.07.28
mappings_channel=parchment

# Other mods
jei_version=19.21.0.247
spectrelib_version=0.17.2+1.21
spectrelib_range=[0.17,0.18)
farmers_delight_neoforge_version=5772720
phc_crops_neoforge_version=5581644
phc_trees_neoforge_version=5616625
the_veggie_way_neoforge_version=5602604
ephero_lib_neoforge_version=5872111
ephero_lib_fabric_version=5439828
croptopia_neoforge_version=5892441
croptopia_fabric_version=5571673
kiwi_neoforge_version=
lychee_neoforge_version=
fruit_trees_neoforge_version=
terrablender_version=5864140
byg_version=5894952
tyg_version=5691181
corgilib_version=5691275
geckolib_version=4.7
architectury_fabric_version=5786326
architectury_neoforge_version=5786327
ld_flower_breeding_version=5933229
create_version=6271847
moonlight_neoforge_version=6285008
supplementaries_neoforge_version=6284266
ie_neoforge_version=6235316

# Mod options
mod_name=ActuallyHarvest
mod_id=actuallyharvest
mod_author=wendall911
license=MIT
mod_description=Working right click harvest. For modded minecraft!
mod_credits=Knoface
mod_url=https://github.com/wendall911/ActuallyHarvest
issue_tracker=https://github.com/wendall911/ActuallyHarvest/issues
mod_update_branch=1.21

# CurseForge/Modrinth Options
release_type=release
release_versions=1.21.4
