# Gradle
org.gradle.jvmargs=-Xmx3G

# Project
version=1.1.3.1
last_mod_version=1.1.2.1
neoforge_mod_version=1.21.1-1.1.3.1-NEOFORGE
fabric_mod_version=1.21.1-1.1.3.1-FABRIC
whitenoise_version=1.21.1.15
whitenoise_range=[1.21.1,1.21.2)
java_version=21

# Common
minecraft_version=1.21.1
mixin_version=0.8.5
mixin_extras_version=0.3.5

# Parchment
# https://parchmentmc.org/docs/getting-started
mappings_version=2024.11.17

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.1.208
neoforge_loader_version_range=[21.0.143,)
neoforge_mc_version_range=[1.21.1, 1.21.2)
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430

# Fabric
fabric_version=0.116.6+1.21.1
fabric_loader_version=0.17.2
fabric_loader_min_version=>=0.15
fabric_mc_version_range=["1.21.1","1.21.2"]
# https://www.curseforge.com/minecraft/mc-mods/modmenu/files/all
mod_menu_version=11.0.3

# Other mods
jei_version=19.21.0.247
farmers_delight_neoforge_version=5772720
phc_crops_neoforge_version=5581644
phc_trees_neoforge_version=5616625
the_veggie_way_neoforge_version=5602604
ephero_lib_neoforge_version=5872111
ephero_lib_fabric_version=5439828
croptopia_neoforge_version=5892441
croptopia_fabric_version=5571673
kiwi_neoforge_version=
lychee_neoforge_version=
fruit_trees_neoforge_version=
terrablender_version=5864140
byg_version=5894952
tyg_version=5691181
corgilib_version=5691275
geckolib_version=4.7
architectury_fabric_version=5786326
architectury_neoforge_version=5786327
ld_flower_breeding_version=5933229
create_version=6271847
moonlight_neoforge_version=6285008
supplementaries_neoforge_version=6284266
ie_neoforge_version=6235316

# Mod options
mod_name=ActuallyHarvest
mod_id=actuallyharvest
mod_author=wendall911
license=MIT
mod_description=Working right click harvest. For modded minecraft!
mod_credits=Knoface
mod_url=https://github.com/wendall911/ActuallyHarvest
issue_tracker=https://github.com/wendall911/ActuallyHarvest/issues
mod_update_branch=1.21.1

# CurseForge/Modrinth Options
release_type=release
release_versions=1.21.1
