plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

def identifier = "${mod_id}-${minecraft_version}-neoforge"
def modLoader = "${project.name}".toUpperCase()
def actualVersion = version
version = "${version}-${modLoader}"

neoForge {
    version = neoforge_version
    validateAccessTransformers = true
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':Common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    implementation group: 'technology.roughness.whitenoise', name: "whitenoise-${minecraft_version}-neoforge", version: "${whitenoise_version}"
    jarJar group: 'technology.roughness.whitenoise', name: "whitenoise-${minecraft_version}-neoforge", version: "${whitenoise_version}"

    runtimeOnly "mezz.jei:jei-${jei_minecraft_version}-neoforge:${jei_version}"

    // Testing mods
    //runtimeOnly "curse.maven:configured-457570:5441232"
    //runtimeOnly "curse.maven:catalogue-459701:5631367"
    //runtimeOnly "curse.maven:farmers_delight-398521:${farmers_delight_neoforge_version}"
    //runtimeOnly "curse.maven:extra_delight-842106:5659546"
    //runtimeOnly "curse.maven:ephero_lib-885449:${ephero_lib_neoforge_version}"
    //runtimeOnly "curse.maven:croptopia-415438:${croptopia_neoforge_version}"
    //runtimeOnly "curse.maven:phc_crops-361385:${phc_crops_neoforge_version}"
    //runtimeOnly "curse.maven:phc_trees-365460:${phc_trees_neoforge_version}"
    //runtimeOnly "curse.maven:terrablender-940057:${terrablender_version}"
    //runtimeOnly "curse.maven:byg-1070751:${byg_version}"
    //runtimeOnly "curse.maven:tyg-962544:${tyg_version}"
    //runtimeOnly "curse.maven:corgilib-693313:${corgilib_version}"
    //runtimeOnly "software.bernie.geckolib:geckolib-neoforge-${minecraft_version}:${geckolib_version}"
    //runtimeOnly "curse.maven:architectury-419699:${architectury_neoforge_version}"
    //runtimeOnly "curse.maven:ldflower-850779:${ld_flower_breeding_version}"
    //runtimeOnly "curse.maven:create-328085:${create_version}"
    //runtimeOnly "curse.maven:moonlight-499980:${moonlight_neoforge_version}"
    //runtimeOnly "curse.maven:supplementaries-412082:${supplementaries_neoforge_version}"
    //runtimeOnly "curse.maven:ie-231951:${ie_neoforge_version}"
    //runtimeOnly "curse.maven:letsdo_brewery-1038106:${letsdo_brewery_neoforge_version}"
    //runtimeOnly "curse.maven:letsdo_herbal-951221:${letsdo_herbal_neoforge_version}"
    //runtimeOnly "curse.maven:letsdo_farm-1038103:${letsdo_farm_neoforge_version}"
    //runtimeOnly "curse.maven:letsdo_vinery-704465:${letsdo_vinery_neoforge_version}"
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

def changelogFile = project(":").projectDir.toString() + '/build/libs/changelog.txt'
def publishFile = project(":").projectDir.toString() + "/NeoForge/build/libs/${identifier}-${version}.jar"
def display_name = "${project.name} ${minecraft_version}-${version}"
def display_version = "${minecraft_version}-${version}"

publishMods {
    file = file(publishFile)
    if (file(changelogFile).exists()) {
        changelog = file(changelogFile).text
    }
    displayName = "${display_name}"
    version = "${display_version}"
    type = "${release_type}".startsWith("release") ? STABLE : ("${release_type}".startsWith("beta") ? BETA : ALPHA)
    modLoaders.add('neoforge')
    dryRun = providers.environmentVariable('DO_RELEASE').getOrNull() == null

    if (project.hasProperty("${curseforge_api_key_prop}")) {
        curseforge {
            accessToken = project.property("${curseforge_api_key_prop}")
            projectId = "${curseforge_id}"
            projectSlug = "${curseforge_slug}"
            javaVersions.add(JavaVersion.toVersion("${java_version}"))
            clientRequired = true
            serverRequired = true
            minecraftVersions.addAll("${release_versions}".split(','))
            optional('betterdays')
            optional('charged-charms')
            optional('creeper-fireworks')
            optional('homeostatic')
            optional('homeostatic-seasons')
            optional('magical-psi-revival')
            optional('mobchampions')
            optional('ready-player-fun')
            optional('simpletextoverlay')
            optional('survivalist-essentials')
            optional('tinkersurvival')
            optional('configured')
            optional('catalogue')
            optional('farmers-delight')
            optional('pams-harvestcraft-2-crops')
            optional('pams-harvestcraft-2-trees')
            optional('fruit-trees')
            optional('croptopia')
            optional('lets-do-brewery-farm-charm-compat')
            optional('lets-do-herbal-brews')
            optional('lets-do-farm-charm')
            optional('lets-do-vinery')
        }
    }
    if (project.hasProperty("${modrinth_api_key_prop}")) {
        modrinth {
            accessToken = project.property("${modrinth_api_key_prop}")
            projectId = "${modrinth_id}"
            minecraftVersions.addAll("${release_versions}".split(','))
            optional('betterdays')
            optional('charged-charms')
            optional('creeper-fireworks-mod')
            optional('homeostatic')
            optional('homeostatic-seasons')
            optional('magical-psi-revival')
            optional('mobchampions')
            optional('ready-player-fun')
            optional('simpletextoverlay')
            optional('survivalist-essentials')
            optional('tinkersurvival')
            optional('farmers-delight')
            optional('fruitful-fun')
            optional('lets-do-brewery-farmcharm-compat')
            optional('lets-do-herbalbrews')
            optional('lets-do-farm-charm')
            optional('lets-do-vinery')
        }
    }
    if (project.hasProperty("${discord_webhook_prop}")) {
        discord {
            webhookUrl = project.property("${discord_webhook_prop}")
            dryRunWebhookUrl = project.property("${discord_dryrun_webhook_prop}")
            username = "${mod_author}"
            content = changelog.map {
                "# A new version of ${mod_display_name} for NeoForge ${minecraft_version} has been released! \n" + it
            }
        }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId project.group
            artifactId "${mod_id}-${minecraft_version}-neoforge"
            version project.version
            // This gives us the built version NeoForge requires
            artifact jar
        }
    }
}
