plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id 'io.github.goooler.shadow'
    id 'se.bjurr.gitchangelog.git-changelog-gradle-plugin'
}

archivesBaseName = "${mod_id}"
version = neoforge_mod_version

neoForge {
    version = neoforge_version
    validateAccessTransformers = true
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':Common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = minecraft_version
        mappingsVersion = mappings_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    implementation group: 'technology.roughness.whitenoise', name: 'whitenoise-neoforge', version: "${whitenoise_version}"
    jarJar group: 'technology.roughness.whitenoise', name: 'whitenoise-neoforge', version: "${whitenoise_version}"

    // Testing mods
    //runtimeOnly "curse.maven:configured-457570:5441232"
    //runtimeOnly "curse.maven:catalogue-459701:5631367"
    //runtimeOnly "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"
    //runtimeOnly "curse.maven:farmers_delight-398521:${farmers_delight_neoforge_version}"
    //runtimeOnly "curse.maven:extra_delight-842106:5659546"
    //runtimeOnly "curse.maven:ephero_lib-885449:${ephero_lib_neoforge_version}"
    //runtimeOnly "curse.maven:croptopia-415438:${croptopia_neoforge_version}"
    //runtimeOnly "curse.maven:the_veggie_way-270684:${the_veggie_way_neoforge_version}"
    //runtimeOnly "curse.maven:phc_crops-361385:${phc_crops_neoforge_version}"
    //runtimeOnly "curse.maven:phc_trees-365460:${phc_trees_neoforge_version}"
    //runtimeOnly "curse.maven:kiwi-303657:${kiwi_neoforge_version}"
    //runtimeOnly "curse.maven:lychee-567403:${lychee_neoforge_version}"
    //runtimeOnly "curse.maven:fruittrees-355467:${fruit_trees_neoforge_version}"
    //runtimeOnly "curse.maven:terrablender-940057:${terrablender_version}"
    //runtimeOnly "curse.maven:byg-1070751:${byg_version}"
    //runtimeOnly "curse.maven:tyg-962544:${tyg_version}"
    //runtimeOnly "curse.maven:corgilib-693313:${corgilib_version}"
    //runtimeOnly "software.bernie.geckolib:geckolib-neoforge-${minecraft_version}:${geckolib_version}"
    //runtimeOnly "curse.maven:architectury-419699:${architectury_neoforge_version}"
    //runtimeOnly "curse.maven:ldflower-850779:${ld_flower_breeding_version}"
    //runtimeOnly "curse.maven:create-328085:${create_version}"
    //runtimeOnly "curse.maven:moonlight-499980:${moonlight_neoforge_version}"
    //runtimeOnly "curse.maven:supplementaries-412082:${supplementaries_neoforge_version}"
    //runtimeOnly "curse.maven:ie-231951:${ie_neoforge_version}"
}

shadowJar {
    archiveClassifier = ''
}

tasks.register('idePostSync') {}

task changelog(type: se.bjurr.gitchangelog.plugin.gradle.GitChangelogTask) {
    file.set(new File(project(":").projectDir.toString() + '/build/libs/changelog.txt'));
    templateContent.set(file(project(":").projectDir.toString() + '/files/templates/changelog.mustache').getText('UTF-8'));
    toRevision.set('HEAD');
    fromRevision.set("${minecraft_version}-${last_mod_version}");
}

def updates = tasks.register("generateUpdates", Copy) {
    it.outputs.upToDateWhen {
        false
    }

    it.from("../files/templates/") {
        include 'updates.json'
        expand 'version': version, 'minecraft_version': minecraft_version
    }

    it.into '../files/'
}

tasks.generateUpdates.mustRunAfter('jar', 'sourcesJar')

tasks.build.dependsOn('changelog', 'generateUpdates')

def changelogFile = project(":").projectDir.toString() + '/build/libs/changelog.txt'
def publishFile = project(":").projectDir.toString() + "/NeoForge/build/libs/${archivesBaseName}-${version}.jar"

publishMods {
    file = file(publishFile)
    changelog = file(changelogFile).text
    type = "${release_type}".startsWith("release") ? STABLE : ("${release_type}".startsWith("beta") ? BETA : ALPHA)
    modLoaders.add('neoforge')
    dryRun = providers.environmentVariable('DO_RELEASE').getOrNull() == null

    if (project.hasProperty('ahcurseApiKey')) {
        curseforge {
            accessToken = project.ahcurseApiKey
            projectId = project.ahcurseId
            javaVersions.add(JavaVersion.toVersion("${java_version}"))
            clientRequired = true
            serverRequired = true
            minecraftVersions.addAll("${release_versions}".split(','))
            embeds('spectrelib')
            optional('configured')
            optional('catalogue')
			optional('farmers-delight')
			optional('pams-harvestcraft-2-crops')
			optional('pams-harvestcraft-2-trees')
			optional('fruit-trees')
			optional('croptopia')
        }
    }
    if (project.hasProperty('ahModrinthId')) {
        modrinth {
            accessToken = project.modrinthKey
            projectId = project.ahModrinthId
            minecraftVersions.addAll("${release_versions}".split(','))
            optional('farmers-delight')
            optional('fruitful-fun')
        }
    }
    if (project.hasProperty('ahGithubToken')) {
    }
}
